### ISSUE TITLE
Support "license" field in package description file

### ISSUE THREAD

**Issue by qjcg** [holocm/holo-build#15]
A "license" field should be supported in package description files.

Currently, using a package description containing the following

```toml
[package]
name = "foo"
version = "1.0"
license = "MIT"
```

results in output as follows after an RPM is installed:

```sh
$ rpm -qi mypackage
Name        : mypackage
Version     : 1.0
License     : None
```
